<?php /** @var array $entities */ ?>
<div class="page-header clearfix">
    <h3 class="page-title pull-left">Dashboard</h3>
    <div class="page-actions pull-right">
        <a href="/customers/new" class="btn btn-default">+ Cliente</a>
        <a href="/products/new" class="btn btn-default">+ Produto</a>
        <a href="/orders/new" class="btn btn-default">+ Venda</a>
    </div>
</div>
<div class="page-content row">
    <div class="col-sm-12">
        <table class="table table-striped">
            <thead>
            <tr>
                <th>Cliente</th>
                <th>Produto</th>
            </tr>
            </thead>
            <tbody>
            <?php if (!$entities) : ?>
                <tr>
                    <td colspan="2">Nenhum pedido cadastrado. Adicione um clicando <a href="/orders/new">aqui</a>
                    </td>
                </tr>
            <?php else: ?>
                <?php foreach ($entities as $entity): /** @var \Crud\Model\Order $entity */ ?>
                    <tr>
                        <td><?php echo $entity->getCustomer()->name . ' <' . $entity->getCustomer()->email . '>'; ?></td>
                        <td><?php echo $entity->getProduct()->name . ' R$' . number_format($entity->getProduct()->price,
                                    2, ',', '.'); ?></td>
                    </tr>
                <?php endforeach; ?>
            <?php endif; ?>
            </tbody>
        </table>
    </div>
</div>
