<?php $entity = isset($entity) ? $entity : new \Crud\Model\Customer() ?>
<div class="page-header clearfix">
    <h3 class="page-title pull-left">
        <?php echo $entity->id ? "Editar {$entity->name}" : 'Novo Cliente' ?>
    </h3>
    <div class="page-actions pull-right">
        <a href="/customers" class="btn btn-default">Voltar</a>
    </div>
</div>
<div class="page-content row">
    <div class="col-sm-12">
        <form action="/customers" class="form-horizontal" method="post" data-validate-form>
            <input type="hidden" name="id" value="<?php echo $entity->id ?>">
            <div class="form-group">
                <label for="name" class="col-sm-2 control-label">Nome</label>
                <div class="col-sm-10">
                    <input type="text" name="name" class="form-control" placeholder="John Doe"
                           required value="<?php echo $entity->name ?>">
                </div>
            </div>
            <div class="form-group">
                <label for="email" class="col-sm-2 control-label">Email</label>
                <div class="col-sm-10">
                    <input type="email" name="email" class="form-control" placeholder="john@email.com"
                           required value="<?php echo $entity->email ?>">
                </div>
            </div>
            <div class="form-group">
                <label for="phone" class="col-sm-2 control-label">Telefone</label>
                <div class="col-sm-10">
                    <input type="text" name="phone" class="form-control" placeholder="(DDD) 1111-1111"
                           data-mask-phone required value="<?php echo $entity->phone ?>">
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-success">Salvar</button>
                </div>
            </div>
        </form>
    </div>
</div>
